#!/usr/bin/env python3

# Build script with pyinstaller

import PyInstaller.__main__
from sys import platform
import os

if platform != "win32":
    print("Building is supported only for Windows. Use 'install' for installation in Linux (or the AUR for ArchLinux).")
    exit()

if not os.path.isfile('resource/restic.exe'):
    print("Download and put restic.exe in ./resource/ before building (see https://github.com/restic/restic/releases)")
    exit()

PyInstaller.__main__.run([
    'resticpy',
    '--console',
    '--distpath','bin',
    '--workpath','.build',
    '--noconfirm',
    '--add-data', 'resource/restic.exe;.'
])
