#!/usr/bin/bash

#Installation directory
PREFIX=/usr/local
while [[ $# -gt 0 ]]; do
  case $1 in
    --prefix)
      PREFIX="$2"
      shift # past argument
      shift # past value
      ;;
    --*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

#Rm resticpy
rm $PREFIX/bin/resticpy
